export const LOCATIONS = [
  "San Francisco",
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "Indianapolis",
  "Seattle",
  "Denver",
  "Washington",
  "Boston",
  "El Paso",
  "Detroit",
  "Nashville",
  "Portland",
  "Memphis",
  "Oklahoma City",
  "Las Vegas",
  "Louisville",
  "Baltimore",
] as const;

export const ROLES = [
  "Product Manager",
  "Software Engineer",
  "Data Scientist",
  "UX Designer",
  "Data Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Fullstack Engineer",
  "Mobile Engineer",
  "DevOps Engineer",
  "QA Engineer",
  "Technical Writer",
  "Technical Recruiter",
  "Sales Engineer",
  "Technical Account Manager",
  "Technical Program Manager",
  "Technical Support Engineer",
  "Technical Sales Engineer",
  "Technical Sales Manager",
] as const;
